all: 1

1: prog1.out
	./prog1.out

2: prog2.out
	./prog2.out

3: prog3.out
	./prog3.out

prog1.out: prog1.c
	gcc prog1.c -o prog1.out

prog2.out: prog2.c
	gcc prog2.c -o prog2.out

prog3.out: prog3.c
	gcc prog3.c -o prog3.out

clear:
	rm *.out
