SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE Equipment;
TRUNCATE TABLE Items;
TRUNCATE TABLE Users;
TRUNCATE TABLE Reservations;
TRUNCATE TABLE Rentals;
TRUNCATE TABLE Notifications;
SET FOREIGN_KEY_CHECKS = 1;
